name: Deploy_backend

on:
  push:
      branches: [ main ]
      paths:
      - 'backend/**'

env:
  AZURE_FUNCTIONAPP_NAME: GetResumeCounterNitin  # set this to your application's name
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'backend'  # setthis to the path to your web app project, defaults to the repository root
  DOTNET_VERSION:'3.1' # set this to the dotnet version to use

  jobs:
      build-and-deploy:
          runs-on: windows-latest
          steps:
          - name: 'Checkout GitHub Action'
            uses: actions/checkout@main

          - name: 'Login via Azure CLI'
            uses: azure/login@v1
            with:
                creds: ${{ secrets.AZURE_CREDENTIALS }}

          - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
            uses: actions/setup-dotnet@v1
            with:
              dotnet-version: ${{ env.DOTNET_VERSION }}

          - name: 'Resolve Project Dependencies using Dotnet'
            shell: pwsh
            run: |
              pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/api'
              dotnet build --configuration Release --output ./output
              popd
          - name: 'Run unit test'
            shell: pwsh
            run: |
               pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/test'
                dotnet build --configuration Release --output ./output
                popd
          - name: 'Run Azure Functions Action'
            uses: Azure/functions-action@v1
            id: fa
            with:
                app-name: ${{ env.AZURE_FUNCTION_NAME }}
                package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/api/output'
                
