name: deploy_frontend
# Deploys when push is made from the frontend folder
on:
    push:
        branches: [ main ]
        paths:
        - 'frontend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: azure/login@v1
      with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Upload to blob storage
      uses: azure/CLI@v1
      with:
        azcliversion: 2.0.73
        inlineScript: |
            az storage blob/upload-batch  -d '$web' -s frontend/ --account-name "azureresumefrontendnitin" --subscription de41d8ff-3b76-4c9b-aba9-0ba4d1f8ca0c
    - name: Purge CDN endpoint
      uses: azure/CLI@v1
      with:
        azcliversion: 2.0.73
        inlineScript: |
           az cdn endpoint purge --content-paths  "/*" --profile-name "nitinazureresume" --name "nitinazureresume" --resource-group "azureresume-rg"

  # Azure logout 
    - name: logout
      run: |
            az logout